import React from 'react';
import { Button } from '../common/Button';

interface DetectionResultProps {
  result: string;
  percentage: number;
  onReportIncorrect: () => void;
}

export const DetectionResult: React.FC<DetectionResultProps> = ({ result, percentage, onReportIncorrect }) => {
  return (
    <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-lg text-center">
      <h2 className="text-2xl font-semibold mb-4">Inference Result: {percentage}% {result}</h2>
      <p className="text-gray-700 mb-6">Your text was likely generated by {result}. If you believe this is incorrect, please report it.</p>
      
      <Button variant="text" onClick={onReportIncorrect}>
        รายงานผลผิดพลาด (Report Incorrect Result)
      </Button>
    </div>
  );
};
