/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        "on-tertiary-container": "#ffd0d2",
        "on-background": "#131b2e",
        "on-surface-variant": "#464555",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "background": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "outline": "#777587",
        "tertiary": "#95002b",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "tertiary-fixed-dim": "#ffb2b7",
        "on-primary-fixed-variant": "#3323cc",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#002113",
        "surface": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "surface-dim": "#d2d9f4",
        "secondary": "#006c49",
        "error-container": "#ffdad6",
        "primary-container": "#4f46e5",
        "tertiary-container": "#bf0f3c",
        "on-primary-container": "#dad7ff",
        "on-surface": "#131b2e",
        "on-tertiary-fixed": "#40000d",
        "secondary-container": "#6cf8bb",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdadb",
        "surface-variant": "#dae2fd",
        "on-tertiary-fixed-variant": "#92002a",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00714d",
        "surface-container-highest": "#dae2fd",
        "on-secondary-fixed-variant": "#005236",
        "primary-fixed": "#e2dfff",
        "outline-variant": "#c7c4d8",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#3525cd",
        "inverse-primary": "#c3c0ff",
        "on-primary-fixed": "#000069",
        "surface-container": "#eaedff"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Inter", "Sarabun", "sans-serif"],
        "body": ["Inter", "Sarabun", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}